name: Build/release

on:
  push:
    branches: 
    - master

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Build/release Electron app
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: |
          npm i -g nrm
          nrm use taobao
          yarn
          yarn build:mac
