name: CI

on: [push]

jobs:
  build-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: CI
        run: |
          export CSC_IDENTITY_AUTO_DISCOVERY=false
          export GH_TOKEN="19e114fb699bd0f3e69dc2d03035539001e5b4b9"
          yarn
          cd npm-package && yarn && cd ..
          yarn build:mac
