name: bulid mac and create release

on: 
  push:
    branches: [master]

jobs:
  build-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
    steps:
      - uses: actions/checkout@v2 # 先检出代码
        
      - name: 初始化node环境
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/ # 如果不配置将影响publish
          
      - name: 安装yarn # 因为我的代码采用了monorepo的 workspace形式 所以必须使用yarn
        run: npm i -g yarn
       
      - name: 安装依赖 # 使用yarn 安装依赖
        run: yarn
      - name: 编译部署ui
        run: yarn build:mac
      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version
      - name: Create Release for Tag
        id: release_tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          tag_name: test-v${{ steps.package-version.outputs.version }}
          release_name: Release test-v${{ steps.package-version.outputs.version }}
          prerelease: false # 是否为预发布版本
          body: |
            成功！
